config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users
  devise_scope :user do
    delete "logout" => "devise/sessions#destroy", :as => "logout"
  end

  resources :users
  resources :links, except: [:index]

  get 'users', to: "users#index", as: "clients"
  get 'users/:id', to: "users#show", as: "client"

  get 'faq' => 'welcome#faq'
  root 'users#show'
end

app/views/layouts/_navbar.html.haml
%nav.navbar.navbar-default
	.container-fluid
		.navbar-header
			%button.navbar-toggle{"data-target" => "#myNavbar", "data-toggle" => "collapse", :type => "button"}
				%span.icon-bar
				%span.icon-bar
				%span.icon-bar
			%a.navbar-brand{:href => "#"} Shoff Accounting Client App
		#myNavbar.collapse.navbar-collapse
			%ul.nav.navbar-nav
				%li.nav-link
					= link_to "Sign In", new_user_session_path if !user_signed_in?
				%li.nav-link
					= link_to "Latest Financial Info", current_user if user_signed_in?
				%li.nav-link
					= link_to "FAQ", faq_path
				%li.nav-link
					= link_to "Sign Out", logout_path, :method => :delete if user_signed_in?

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content =>        "text/html; charset=UTF-8", "http-equive" => "Content-Type"}/
    %meta{:content =>        "width=device-width, initial-scale=1", :name => "viewport"}/
    %title Shoff Accounting Client App
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    = csrf_meta_tags
    = favicon_link_tag       'favicon.ico'
  %body
    .container
      -# Nav Row
      .row
        = render :partial => 'layouts/navbar'
      -# Yield Row
      = yield